matrix:
  include:
    - language: python
      python: 3.8
      script: 
        - pip install pipenv
        - pipenv install

    - language: node_js
      node_js:
        - "stable"
      before_script:
      - cd frontend
      - npm install
      - npm run build